//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFDS.KMPortal.Webparts.TopCandLWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class TopCandLWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(TopCandLWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::IFDS.KMPortal.Webparts.TopCandLWebPart.TopCandLWebPart @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n\r\n<script type=\"text/javascript\">\r\n    //<![CDATA[\r    var _departmentmasterl" +
                    "istjsondata = \'");
                                  @__w.Write(DepartmentMasterListJSON );

            @__w.Write("\';\r\n    var _departmentmasterlistsiteurl = \'");
                                 @__w.Write(DepartmentMasterListSiteUrl );

            @__w.Write("\';\r\n    var _topcontributorsjsondata = \'");
                             @__w.Write(TopContributorsListJSON );

            @__w.Write("\';\r\n    var _toplearnersjsondata = \'");
                         @__w.Write(TopLearnersListJSON );

            @__w.Write("\';\r\n    var _topcontributorslistname = \'");
                             @__w.Write(TopContributorsListName );

            @__w.Write("\';\r\n    var _topcontributorsalldeptlistname = \'");
                                    @__w.Write(TopContributorsAllDeptListName );

            @__w.Write("\';\r\n    var _toplearnerslistname = \'");
                         @__w.Write(TopLearnersListName  );

            @__w.Write("\';\r\n    var _topcontributorsrowlimit = \'");
                             @__w.Write(TopContributorsItemCount );

            @__w.Write("\';\r\n    var _toplearnersrowlimit = \'");
                         @__w.Write(TopLearnersItemCount  );

            @__w.Write("\';\r\n    var _isglobalsitetopcandl = \'");
                          @__w.Write(IsTopCandLGlobalSite  );

            @__w.Write("\';\r\n    var _topcontributorstabname = \'");
                            @__w.Write(TopCandLTab1 );

            @__w.Write("\';\r\n    var _toplearnerstabname = \'");
                        @__w.Write(TopCandLTab2 );

            @__w.Write("\';\r\n    var _topcandlactivetab = null;\r\n    var _noDataMessage = \'");
                   @__w.Write(NoDataMessage );

            @__w.Write("\';\r\n    var _departmentName = \'");
                    @__w.Write(_deptname );

            @__w.Write("\';\r\n    var _errMessage = \'");
                @__w.Write(TopCandLErrMsg );

            @__w.Write(@"';
    //]]></script>

<div class=""widgetWrapperHeight"" id=""TopCandL"">
    <div class=""panel-heading top-bar"">
        <div class=""sub-caption"">
            <span class=""topicon""></span>
            <!--   <img src=""images/top-icon.png""> -->
            <span class=""panel-title"">");
                              @__w.Write(TopCandLWidgetTitle );

            @__w.Write("</span>\r\n            <a class=\"help-icon\" href=\"#\" data-placement=\"top\" data-togg" +
                    "le=\"tooltip\" data-container=\"body\" data-html=\"true\" title=\'");
                                                                                                                           @__w.Write(TopCandLToolTipMsg);

            @__w.Write("\'></a>\r\n            \r\n            <a href=\'");
             @__w.Write(_initialviewallurl );

            @__w.Write(@"' target=""_blank"" class=""more-globl link-bgcolor"" id=""topcandlviewalllink"">View All</a>
            
        </div>
        <div id=""topcandldwblock"">
            <span class=""dptselect"">Select Department</span>
            <div class=""topdpmenu"">
                <div class=""dropdown"">
                    <button class=""btn btn-default dropdown-toggle dpt-btn"" type=""button"" id=""topcandlbutton"" data-toggle=""dropdown"" data-hover=""dropdown"">
                        All Departments
                            <span class=""caret white aerowdown""></span>
                    </button>
                    <ul class=""dropdown-menu top-selectdown"" role=""menu"" aria-labelledby=""Top"" id=""topcandldropdown"">
                    </ul>
                </div>
            </div>
        </div>

    </div>
    <div id=""topcandltabblock"" class=""panel-bgcolor"">

        <ul class=""tb-border"" id=""topcandltab"">
            <li class=""active""><a data-toggle=""tab"" href=""#contributors"" id=""tab1"">");
                                                                           @__w.Write(TopCandLTab1);

            @__w.Write("</a></li>\r\n            <li><a data-toggle=\"tab\" href=\"#learners\" id=\"tab2\">");
                                                        @__w.Write(TopCandLTab2);

            @__w.Write("</a></li>\r\n        </ul>\r\n\r\n\r\n        <div class=\"tab-content\">\r\n            <div" +
                    " id=\"contributors\" class=\"tab-pane fade in active\">\r\n                <div class=" +
                    "\"outer top-scroll etratop\">\r\n                    <div class=\"scrolldiv forumdiv\"" +
                    " id=\"topcontributorsappend\">\r\n                    </div>\r\n\r\n                </di" +
                    "v>\r\n            </div>\r\n            <div id=\"learners\" class=\"tab-pane fade in\">" +
                    "\r\n                <div class=\"outer top-scroll etratop\">\r\n                    <d" +
                    "iv class=\"scrolldiv forumdiv\" id=\"toplearnersappend\">\r\n                    </div" +
                    ">\r\n                </div>\r\n\r\n\r\n\r\n            </div>\r\n        </div>\r\n    </div>\r" +
                    "\n\r\n</div>\r\n<script>\r\n\r    jQuery.noConflict();\r\r    (function ($) {\r\n\r        $(" +
                    "document).ready(function () {\r\n\r\n            ChangeTabColor();\r\n\r\n            if" +
                    " (_isglobalsitetopcandl.toLowerCase() === \'false\') {\r\n                $(\"#topcan" +
                    "dldwblock\").hide();\r\n                $(\'#TopCandL\').addClass(\"widgetWrapperHeigh" +
                    "t\");\r\n            }\r\n\r\n            getDepartmentsDropdown();\r\n\r\n            getT" +
                    "opContributors();\r\n\r\n            $(\'a[href=\"#contributors\"]\').click(function (e)" +
                    " {\r\n                var tabNameTopcontrib = $(this).text();\r\n                upd" +
                    "ateviewallurl(tabNameTopcontrib);\r\n            });\r\n\r\n            $(\'a[href=\"#le" +
                    "arners\"]\').click(function (e) {\r\n                if (_isglobalsitetopcandl.toLow" +
                    "erCase() === \'true\') {\r\n                    getTopLearnersAjax();\r\n             " +
                    "   } else {\r\n                    getTopLearners();\r\n                }\r\n         " +
                    "       var tabNameTopLearn = $(this).text();\r\n                updateviewallurl(t" +
                    "abNameTopLearn);\r\n\r\n            });\r\n\r\n            $(\".dropdown-menu li a\").clic" +
                    "k(function () {\r\n                $(this).parents(\".dropdown\").find(\'.btn\').html(" +
                    "$(this).text());\r\n                $(this).parents(\".dropdown\").find(\'.btn\').val(" +
                    "$(this).data(\'value\'));\r\n                $(\"#topcandlbutton\").change();\r\n       " +
                    "     });\r\n\r\n            $(\"#topcandlbutton\").change(function () {\r\n\r\n           " +
                    "     var topcandlactivetab = $(\"ul#topcandltab li.active\").text();\r\n            " +
                    "    updateviewallurl(topcandlactivetab);\r\n\r\n                getTopContributorsAj" +
                    "ax();\r\n\r\n                getTopLearnersAjax();\r\n\r\n            });\r\n\r\n        });" +
                    "\r\n\r\n        /**\r\n        * Populate Departments dropdown\r\n        *\r\n        */\r" +
                    "\n        function ChangeTabColor() {\r\n            if (_isglobalsitetopcandl == \'" +
                    "True\') {\r\n                $(\"#topcandltab\").addClass(\'nav nav-tabs tb-border\');\r" +
                    "\n            }\r\n            else {\r\n                $(\"#topcandltab\").addClass(\'" +
                    "nav nav-tabs dpttab\');\r\n            }\r\n        }\r\n\r\n        /**\r\n        * Popul" +
                    "ate Departments dropdown\r\n        *\r\n        */\r\n        function getDepartments" +
                    "Dropdown() {\r\n            var htmlDept = [];\r\n            $.each(eval(_departmen" +
                    "tmasterlistjsondata), function (index, element) {\r\n                htmlDept = ht" +
                    "mlDept + \'<li role=\"presentation\"><a role=\"menuitem\" tabindex=\"-1\" href=\"#\">\' + " +
                    "element.Department + \'</a></li>\';\r\n            });\r\n\r\n            $(\"#topcandldr" +
                    "opdown\").append(htmlDept);\r\n        }\r\n\r\n\r\n        /**\r\n        * Retrieve Top C" +
                    "ontrinbutors from Custom List\r\n        *\r\n        */\r\n        function getTopCon" +
                    "tributors() {\r\n            var errorMessage = eval(_toplearnersjsondata)[1].Mess" +
                    "age;\r\n            if (errorMessage.length > 0) {\r\n                $(\"#topcontrib" +
                    "utorsappend\").append(errorMessage);\r\n            }\r\n            else\r\n          " +
                    "      if (eval(_topcontributorsjsondata)[0].Results.length === 0) {\r\n           " +
                    "         $(\"#topcontributorsappend\").html(\'\');\r\n                    $(\"#topcontr" +
                    "ibutorsappend\").append(_noDataMessage);\r\n                } else {\r\n             " +
                    "       var htmltopCon = [];\r\n                    $.each(eval(_topcontributorsjso" +
                    "ndata)[0].Results, function (index, element) {\r\n                        htmltopC" +
                    "on = htmltopCon + \'<div class=\"docinfo\"><div class=\"usrbox-top\"><div class=\"topu" +
                    "ser-detail\"><table><th></th><tbody class=\"topctb\"><tr>\'\r\n                       " +
                    "  + \'<td class=\"skyblue user-txt\"><a href=\"\' + element.personalurl + \'\">\' + elem" +
                    "ent.Member + \'</a></td><td class=\"countxt\"><span class=\"count\">\' + element.NoOfD" +
                    "iscussions + \'</span> Discussions</td>\'\r\n                         + \'</tr><tr><t" +
                    "d class=\"blue\"><span class=\"msg\"></span><span>\' + element.emailaddress + \'</span" +
                    "></td><td class=\"countxt\"><span class=\"count\">\' +\r\n                         elem" +
                    "ent.NoOfReplies + \'</span> Replies</td></tr><tr><td><span class=\"mbl\"></span><sp" +
                    "an>\' + element.phonenumber + \'</span> </td><td class=\"countxt\"><span class=\"repl" +
                    "ies\"></span><span>\' + element.GiftedBadgeText + \'</span></td>\'\r\n                " +
                    "         + \'</tr></tbody></table></div></div></div>\';\r\n                    });\r\n" +
                    "                    $(\"#topcontributorsappend\").append(htmltopCon);\r\n           " +
                    "     }\r\n            var tabNameTopcontribLoad = $(\"ul#topcandltab li.active\").te" +
                    "xt();\r\n            updateviewallurl(tabNameTopcontribLoad);\r\n        }\r\n\r\n      " +
                    "  /**\r\n        * Retrieve Top Learners from External List.\r\n        *\r\n        *" +
                    " @version 1.0.0\r\n        */\r\n        function getTopLearners() {\r\n            va" +
                    "r htmlTopLearn = [];\r\n\r\n            var errorMessage = eval(_toplearnersjsondata" +
                    ")[1].Message;\r\n\r\n            if (errorMessage.length > 0) {\r\n                $(\"" +
                    "#toplearnersappend .mCSB_container\").empty().append(errorMessage);\r\n            " +
                    "}\r\n            else\r\n                if (eval(_toplearnersjsondata)[0].Results =" +
                    "== undefined || eval(_toplearnersjsondata)[0].Results === null || eval(_toplearn" +
                    "ersjsondata)[0].Results == 0) {\r\n                    $(\"#toplearnersappend .mCSB" +
                    "_container\").empty().append(_noDataMessage);\r\n                } else {\r\n        " +
                    "            var htmlTopLearn = [];\r\n                    $.each(eval(_toplearners" +
                    "jsondata)[0].Results, function (index, element) {\r\n                        htmlT" +
                    "opLearn = htmlTopLearn + \'<div class=\"docinfo\"><div class=\"usrbox-top\"><div clas" +
                    "s=\"topuser-detail\"><table><th></th><tbody class=\"topctb\"><tr>\'\r\n                " +
                    "         + \'<td class=\"skyblue user-txt\"><a href=\"\' + element.personalurl + \'\">\'" +
                    " + element.displayname + \'</a></td><td class=\"countxt\"><span class=\"count\">\' + e" +
                    "lement.column1 + \'</span> Discussions Views</td>\'\r\n                         + \'<" +
                    "/tr><tr><td class=\"blue\"><span class=\"msg\"></span><span>\' + element.emailaddress" +
                    " + \'</span></td><td class=\"countxt\"><span class=\"count\">\' +\r\n                   " +
                    "      element.column2 + \'</span> FAQ Views </td></tr><tr><td><span class=\"mbl\"><" +
                    "/span><span>\' + element.phonenumber + \'</span> </td><td class=\"countxt\"></td>\'\r\n" +
                    "                         + \'</tr></tbody></table></div></div></div>\';\r\n         " +
                    "           });\r\n                    $(\"#toplearnersappend .mCSB_container\").empt" +
                    "y().append(htmlTopLearn);\r\n                }\r\n        }\r\n\r\n        /**\r\n        " +
                    "* Retrieve Top Contrinbutors from Custom List.\r\n        *\r\n        * @version 1." +
                    "0.0\r\n        */\r\n        function getTopContributorsAjax() {\r\n\r\n            var " +
                    "htmlTopContributors = [];\r\n\r\n            var department = $(\"#topcandlbutton\").t" +
                    "ext().trim();\r\n\r\n            deptobj = getObjects(eval(_departmentmasterlistjson" +
                    "data), \'Department\', department);\r\n\r\n            if (department.toLowerCase() ==" +
                    "= \'all departments\') {\r\n                this.listtoquery = _topcontributorsallde" +
                    "ptlistname;\r\n            }\r\n            else {\r\n                this.listtoquery" +
                    " = _topcontributorslistname;\r\n            }\r\n\r\n            var topcquery = { sit" +
                    "eurl: deptobj[0].siteurl, topcontributorslistname: this.listtoquery, rowlimit: _" +
                    "topcontributorsrowlimit, propErrorMessage: _errMessage };\r\n\r\n            $.ajax(" +
                    "{\r\n                type: \"POST\",\r\n                async: true,\r\n                " +
                    "contentType: \"application/json; charset=utf-8\",\r\n                data: JSON.stri" +
                    "ngify(topcquery),\r\n                url: \"/_Layouts/15/IFDS.KMPortal/WebMethodHel" +
                    "per.aspx/GetTopContributors\",\r\n                success: function (msg) {\r\n      " +
                    "              var temp = JSON.parse(msg.d);\r\n                    var errorMessag" +
                    "e = temp[1].Message;\r\n                    if (errorMessage.length > 0) {\r\n      " +
                    "                  $(\"#topcontributorsappend .mCSB_container\").empty().append(err" +
                    "orMessage);\r\n                    }\r\n                    else\r\n                  " +
                    "      if (temp[0].Results === undefined || temp[0].Results === null || temp[0].R" +
                    "esults == 0) {\r\n                            $(\"#topcontributorsappend .mCSB_cont" +
                    "ainer\").empty().append(_noDataMessage);\r\n                        } else {\r\n     " +
                    "                       $.each(temp[0].Results, function (index, element) {\r\n    " +
                    "                            htmlTopContributors = htmlTopContributors + \'<div cl" +
                    "ass=\"docinfo\"><div class=\"usrbox-top\"><div class=\"topuser-detail\"><table><th></t" +
                    "h><tbody class=\"topctb\"><tr>\'\r\n                                 + \'<td class=\"sk" +
                    "yblue user-txt\"><a href=\"\' + element.personalurl + \'\">\' + element.Member + \'</a>" +
                    "</td><td class=\"countxt\"><span class=\"count\">\' + element.NoOfDiscussions + \'</sp" +
                    "an> Discussions</td>\'\r\n                                 + \'</tr><tr><td class=\"b" +
                    "lue\"><span class=\"msg\"></span><span>\' + element.emailaddress + \'</span></td><td " +
                    "class=\"countxt\"><span class=\"count\">\' +\r\n                                 elemen" +
                    "t.NoOfReplies + \'</span> Replies</td></tr><tr><td><span class=\"mbl\"></span><span" +
                    ">\' + element.phonenumber + \'</span> </td><td class=\"countxt\"><span class=\"replie" +
                    "s\"></span><span>\' + element.GiftedBadgeText + \'</span></td>\'\r\n                  " +
                    "               + \'</tr></tbody></table></div></div></div>\';\r\n                   " +
                    "         });\r\n                            $(\"#topcontributorsappend .mCSB_contai" +
                    "ner\").empty().append(htmlTopContributors);\r\n                        }\r\n         " +
                    "       },\r\n                error: function (msg) {\r\n                    //alert(" +
                    "\"error in getContributors\" + msg);\r\n                }\r\n            });\r\n\r\n\r\n    " +
                    "    }\r\n\r\n        /**\r\n        * Retrieve Top Learners from External List.\r\n     " +
                    "   *\r\n        * @version 1.0.0\r\n        */\r\n        function getTopLearnersAjax(" +
                    ") {\r\n            var htmlTopLearners = [];\r\n            var department = $(\"#top" +
                    "candlbutton\").text().trim();\r\n            var toplquery = { siteurl: _department" +
                    "masterlistsiteurl, toplearnerslistname: _toplearnerslistname, rowlimit: _toplear" +
                    "nersrowlimit, departmentname: department, propErrorMessage: _errMessage };\r\n    " +
                    "        $.ajax({\r\n                type: \"POST\",\r\n                async: true,\r\n " +
                    "               contentType: \"application/json; charset=utf-8\",\r\n                " +
                    "data: JSON.stringify(toplquery),\r\n                url: \"/_Layouts/15/IFDS.KMPort" +
                    "al/WebMethodHelper.aspx/GetTopLearners\",\r\n                success: function (msg" +
                    ") {\r\n                    var temp = JSON.parse(msg.d);\r\n                    var " +
                    "errorMessage = temp[1].Message;\r\n                    if (errorMessage.length > 0" +
                    ") {\r\n                        $(\"#toplearnersappend .mCSB_container\").empty().app" +
                    "end(errorMessage);\r\n                    }\r\n                    else\r\n           " +
                    "             if (temp[0].Results === undefined || temp[0].Results === null || te" +
                    "mp[0].Results == 0) {\r\n                            $(\"#toplearnersappend .mCSB_c" +
                    "ontainer\").empty().append(_noDataMessage);\r\n                        } else {\r\n  " +
                    "                          $.each(temp[0].Results, function (index, element) {\r\n " +
                    "                               htmlTopLearners = htmlTopLearners + \'<div class=\"" +
                    "docinfo\"><div class=\"usrbox-top\"><div class=\"topuser-detail\"><table><th></th><tb" +
                    "ody class=\"topctb\"><tr>\'\r\n                                 + \'<td class=\"skyblue" +
                    " user-txt\"><a href=\"\' + element.personalurl + \'\">\' + element.displayname + \'</a>" +
                    "</td><td class=\"countxt\"><span class=\"count\">\' + element.column1 + \'</span> Disc" +
                    "ussions Views</td>\'\r\n                                 + \'</tr><tr><td class=\"blu" +
                    "e\"><span class=\"msg\"></span><span>\' + element.emailaddress + \'</span></td><td cl" +
                    "ass=\"countxt\"><span class=\"count\">\' +\r\n                                 element." +
                    "column2 + \'</span> FAQ Views</td></tr><tr><td><span class=\"mbl\"></span><span>\' +" +
                    " element.phonenumber + \'</span> </td><td class=\"countxt\"></td>\'\r\n               " +
                    "                  + \'</tr></tbody></table></div></div></div>\';\r\n\r\n              " +
                    "              });\r\n                            $(\"#toplearnersappend .mCSB_conta" +
                    "iner\").empty().append(htmlTopLearners);\r\n                        }\r\n            " +
                    "    },\r\n                error: function (msg) {\r\n                    //alert(\"er" +
                    "ror in getTopLearners\" + msg);\r\n                }\r\n            });\r\n        }\r\n\r" +
                    "\n\r\n        /**\r\n        * update view all link of top learners and top contribut" +
                    "ors.\r\n        *\r\n        * @version 1.0.0\r\n        */\r\n        function updatevi" +
                    "ewallurl(tabName) {\r\n            var department;\r\n            // var _topcandlac" +
                    "tivetab = $(\"ul#topcandltab li.active\").text();\r\n            var _topcandlactive" +
                    "tab = tabName;\r\n            if (_isglobalsitetopcandl == \'True\') {\r\n            " +
                    "    department = $(\"#topcandlbutton\").text();\r\n            }\r\n            else {" +
                    "\r\n                department = _departmentName;\r\n            }\r\n            var " +
                    "siteurltemp = getObjects(eval(_departmentmasterlistjsondata), \'Department\', depa" +
                    "rtment.trim());\r\n            if (_topcandlactivetab === _topcontributorstabname)" +
                    " {\r\n                var siteurltoredirect = siteurltemp[0].siteurl + \"Lists/Memb" +
                    "ers/MembersAllItems.aspx\";\r\n                if (department.trim().toLowerCase() " +
                    "=== \"all departments\") {\r\n                    siteurltoredirect = _departmentmas" +
                    "terlistsiteurl + \"Lists/TopContributorsGlobal/AllItems.aspx\";\r\n                }" +
                    "\r\n                $(\'#topcandlviewalllink\').attr(\"href\", siteurltoredirect);\r\n  " +
                    "          } else if (_topcandlactivetab === _toplearnerstabname) {\r\n            " +
                    "    var siteurltctoredirect = _departmentmasterlistsiteurl + \"pages/TopLearnersF" +
                    "ilter.aspx\" + \"?web=\" + department.trim();\r\n\r\n                if (department.tri" +
                    "m().toLowerCase() === \"all departments\") {\r\n                    siteurltctoredir" +
                    "ect = _departmentmasterlistsiteurl + \"Lists/\" + _toplearnerslistname + \"/KMP_Z_T" +
                    "opLearnersRead%20List.aspx\";\r\n                }\r\n                $(\'#topcandlvie" +
                    "walllink\').attr(\"href\", siteurltctoredirect);\r\n            }\r\n        }\r\n\r\n\r\n   " +
                    "     /**\r\n        * parse json data and return objects.\r\n        *\r\n        * @v" +
                    "ersion 1.0.0\r\n        */\r\n        function getObjects(obj, key, val) {\r\n        " +
                    "    var objects = [];\r\n            for (var i in obj) {\r\n                if (!ob" +
                    "j.hasOwnProperty(i)) continue;\r\n                if (typeof obj[i] == \'object\') {" +
                    "\r\n                    objects = objects.concat(getObjects(obj[i], key, val));\r\n " +
                    "               } else if (i == key && obj[key] == val) {\r\n                    ob" +
                    "jects.push(obj);\r\n                }\r\n            }\r\n            return objects;\r" +
                    "\n        }\r\n\r\n\r\n    })(jQuery);\r\n</script>\r\n");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
