//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService", ConfigurationName="PACEPartnerServiceDetails.GetDetailsWebServiceSoap")]
    public interface GetDetailsWebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService/GetDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse GetDetails(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService/GetDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse> GetDetailsAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string corpNameField;
        
        private string userIdField;
        
        private string signatureField;
        
        private string headerSaltField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CorpName {
            get {
                return this.corpNameField;
            }
            set {
                this.corpNameField = value;
                this.RaisePropertyChanged("CorpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string HeaderSalt {
            get {
                return this.headerSaltField;
            }
            set {
                this.headerSaltField = value;
                this.RaisePropertyChanged("HeaderSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class SessionDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionLOIDField;
        
        private int sessionLocatorNumberField;
        
        private int sessionSeatsField;
        
        private bool sessionWaitlistField;
        
        private string sessionDurationField;
        
        private string sessionLocationField;
        
        private string sessionStartDateField;
        
        private string sessionStartTimeField;
        
        private string sessionEndDateField;
        
        private string sessionEndTimeField;
        
        private string sessionTimeZoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionLOID {
            get {
                return this.sessionLOIDField;
            }
            set {
                this.sessionLOIDField = value;
                this.RaisePropertyChanged("SessionLOID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int SessionLocatorNumber {
            get {
                return this.sessionLocatorNumberField;
            }
            set {
                this.sessionLocatorNumberField = value;
                this.RaisePropertyChanged("SessionLocatorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SessionSeats {
            get {
                return this.sessionSeatsField;
            }
            set {
                this.sessionSeatsField = value;
                this.RaisePropertyChanged("SessionSeats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool SessionWaitlist {
            get {
                return this.sessionWaitlistField;
            }
            set {
                this.sessionWaitlistField = value;
                this.RaisePropertyChanged("SessionWaitlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SessionDuration {
            get {
                return this.sessionDurationField;
            }
            set {
                this.sessionDurationField = value;
                this.RaisePropertyChanged("SessionDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SessionLocation {
            get {
                return this.sessionLocationField;
            }
            set {
                this.sessionLocationField = value;
                this.RaisePropertyChanged("SessionLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SessionStartDate {
            get {
                return this.sessionStartDateField;
            }
            set {
                this.sessionStartDateField = value;
                this.RaisePropertyChanged("SessionStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SessionStartTime {
            get {
                return this.sessionStartTimeField;
            }
            set {
                this.sessionStartTimeField = value;
                this.RaisePropertyChanged("SessionStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string SessionEndDate {
            get {
                return this.sessionEndDateField;
            }
            set {
                this.sessionEndDateField = value;
                this.RaisePropertyChanged("SessionEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string SessionEndTime {
            get {
                return this.sessionEndTimeField;
            }
            set {
                this.sessionEndTimeField = value;
                this.RaisePropertyChanged("SessionEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string SessionTimeZone {
            get {
                return this.sessionTimeZoneField;
            }
            set {
                this.sessionTimeZoneField = value;
                this.RaisePropertyChanged("SessionTimeZone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class PartDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string scheduleIDField;
        
        private string partDurationField;
        
        private string partLocationField;
        
        private string partStartDateField;
        
        private string partStartTimeField;
        
        private string partEndDateField;
        
        private string partEndTimeField;
        
        private string partTimeZoneField;
        
        private string partInstructorField;
        
        private string totalPartBreakField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ScheduleID {
            get {
                return this.scheduleIDField;
            }
            set {
                this.scheduleIDField = value;
                this.RaisePropertyChanged("ScheduleID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PartDuration {
            get {
                return this.partDurationField;
            }
            set {
                this.partDurationField = value;
                this.RaisePropertyChanged("PartDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PartLocation {
            get {
                return this.partLocationField;
            }
            set {
                this.partLocationField = value;
                this.RaisePropertyChanged("PartLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PartStartDate {
            get {
                return this.partStartDateField;
            }
            set {
                this.partStartDateField = value;
                this.RaisePropertyChanged("PartStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PartStartTime {
            get {
                return this.partStartTimeField;
            }
            set {
                this.partStartTimeField = value;
                this.RaisePropertyChanged("PartStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PartEndDate {
            get {
                return this.partEndDateField;
            }
            set {
                this.partEndDateField = value;
                this.RaisePropertyChanged("PartEndDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string PartEndTime {
            get {
                return this.partEndTimeField;
            }
            set {
                this.partEndTimeField = value;
                this.RaisePropertyChanged("PartEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PartTimeZone {
            get {
                return this.partTimeZoneField;
            }
            set {
                this.partTimeZoneField = value;
                this.RaisePropertyChanged("PartTimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PartInstructor {
            get {
                return this.partInstructorField;
            }
            set {
                this.partInstructorField = value;
                this.RaisePropertyChanged("PartInstructor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TotalPartBreak {
            get {
                return this.totalPartBreakField;
            }
            set {
                this.totalPartBreakField = value;
                this.RaisePropertyChanged("TotalPartBreak");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class SectionDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sectionTitleField;
        
        private string sectionInstructionsField;
        
        private int sectionRequiredField;
        
        private int sectionTotalField;
        
        private int itemSequenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SectionTitle {
            get {
                return this.sectionTitleField;
            }
            set {
                this.sectionTitleField = value;
                this.RaisePropertyChanged("SectionTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SectionInstructions {
            get {
                return this.sectionInstructionsField;
            }
            set {
                this.sectionInstructionsField = value;
                this.RaisePropertyChanged("SectionInstructions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int SectionRequired {
            get {
                return this.sectionRequiredField;
            }
            set {
                this.sectionRequiredField = value;
                this.RaisePropertyChanged("SectionRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SectionTotal {
            get {
                return this.sectionTotalField;
            }
            set {
                this.sectionTotalField = value;
                this.RaisePropertyChanged("SectionTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ItemSequence {
            get {
                return this.itemSequenceField;
            }
            set {
                this.itemSequenceField = value;
                this.RaisePropertyChanged("ItemSequence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class LoDetailsWithinCurriculum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string lOIDWithinCurriculumField;
        
        private string lOTitleWithinCurriculumField;
        
        private string lODescriptionWithinCurriculumField;
        
        private int itemSequenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LOIDWithinCurriculum {
            get {
                return this.lOIDWithinCurriculumField;
            }
            set {
                this.lOIDWithinCurriculumField = value;
                this.RaisePropertyChanged("LOIDWithinCurriculum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LOTitleWithinCurriculum {
            get {
                return this.lOTitleWithinCurriculumField;
            }
            set {
                this.lOTitleWithinCurriculumField = value;
                this.RaisePropertyChanged("LOTitleWithinCurriculum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LODescriptionWithinCurriculum {
            get {
                return this.lODescriptionWithinCurriculumField;
            }
            set {
                this.lODescriptionWithinCurriculumField = value;
                this.RaisePropertyChanged("LODescriptionWithinCurriculum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int ItemSequence {
            get {
                return this.itemSequenceField;
            }
            set {
                this.itemSequenceField = value;
                this.RaisePropertyChanged("ItemSequence");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class AvailableLanguage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageField;
        
        private string languageIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LanguageID {
            get {
                return this.languageIDField;
            }
            set {
                this.languageIDField = value;
                this.RaisePropertyChanged("LanguageID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class Subject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string titleField;
        
        private string titleWithHierarchyField;
        
        private string parentIdField;
        
        private string parentTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TitleWithHierarchy {
            get {
                return this.titleWithHierarchyField;
            }
            set {
                this.titleWithHierarchyField = value;
                this.RaisePropertyChanged("TitleWithHierarchy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("ParentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParentTitle {
            get {
                return this.parentTitleField;
            }
            set {
                this.parentTitleField = value;
                this.RaisePropertyChanged("ParentTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultMaterial))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultSession))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultCurriculum))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultTest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CatalogResultOnlineCourse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public abstract partial class CatalogResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Subject[] subjectsField;
        
        private AvailableLanguage[] availableLanguagesField;
        
        private string objectIdField;
        
        private CatalogType typeField;
        
        private string titleField;
        
        private string providerField;
        
        private string descrField;
        
        private string deepLinkURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Subject[] Subjects {
            get {
                return this.subjectsField;
            }
            set {
                this.subjectsField = value;
                this.RaisePropertyChanged("Subjects");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public AvailableLanguage[] AvailableLanguages {
            get {
                return this.availableLanguagesField;
            }
            set {
                this.availableLanguagesField = value;
                this.RaisePropertyChanged("AvailableLanguages");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("ObjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public CatalogType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("Provider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
                this.RaisePropertyChanged("Descr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DeepLinkURL {
            get {
                return this.deepLinkURLField;
            }
            set {
                this.deepLinkURLField = value;
                this.RaisePropertyChanged("DeepLinkURL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public enum CatalogType {
        
        /// <remarks/>
        ONLINE = 1,
        
        /// <remarks/>
        EVENT = 2,
        
        /// <remarks/>
        QUICKCOURSE = 4,
        
        /// <remarks/>
        CURRICULUM = 8,
        
        /// <remarks/>
        TEST = 16,
        
        /// <remarks/>
        SESSION = 32,
        
        /// <remarks/>
        LIBRARY = 64,
        
        /// <remarks/>
        POSTING = 128,
        
        /// <remarks/>
        MATERIAL = 256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultMaterial : CatalogResult {
        
        private Field[] fieldsField;
        
        private string materialTypeField;
        
        private string priceCurrencyField;
        
        private decimal priceAmountField;
        
        private string durationField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
                this.RaisePropertyChanged("MaterialType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PriceCurrency {
            get {
                return this.priceCurrencyField;
            }
            set {
                this.priceCurrencyField = value;
                this.RaisePropertyChanged("PriceCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal PriceAmount {
            get {
                return this.priceAmountField;
            }
            set {
                this.priceAmountField = value;
                this.RaisePropertyChanged("PriceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultEvent : CatalogResult {
        
        private SessionDetails[] sessionsField;
        
        private Field[] fieldsField;
        
        private string eventNumberField;
        
        private string objectivesField;
        
        private string durationField;
        
        private string priceCurrencyField;
        
        private decimal priceAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public SessionDetails[] Sessions {
            get {
                return this.sessionsField;
            }
            set {
                this.sessionsField = value;
                this.RaisePropertyChanged("Sessions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EventNumber {
            get {
                return this.eventNumberField;
            }
            set {
                this.eventNumberField = value;
                this.RaisePropertyChanged("EventNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Objectives {
            get {
                return this.objectivesField;
            }
            set {
                this.objectivesField = value;
                this.RaisePropertyChanged("Objectives");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PriceCurrency {
            get {
                return this.priceCurrencyField;
            }
            set {
                this.priceCurrencyField = value;
                this.RaisePropertyChanged("PriceCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal PriceAmount {
            get {
                return this.priceAmountField;
            }
            set {
                this.priceAmountField = value;
                this.RaisePropertyChanged("PriceAmount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultSession : CatalogResult {
        
        private PartDetails[] partsField;
        
        private Field[] fieldsField;
        
        private int locatorNumberField;
        
        private int seatsField;
        
        private int maxRegistrationField;
        
        private int currentlyRegisteredField;
        
        private int waitlistField;
        
        private string durationField;
        
        private string languageField;
        
        private string trainingContactField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public PartDetails[] Parts {
            get {
                return this.partsField;
            }
            set {
                this.partsField = value;
                this.RaisePropertyChanged("Parts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LocatorNumber {
            get {
                return this.locatorNumberField;
            }
            set {
                this.locatorNumberField = value;
                this.RaisePropertyChanged("LocatorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("Seats");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int MaxRegistration {
            get {
                return this.maxRegistrationField;
            }
            set {
                this.maxRegistrationField = value;
                this.RaisePropertyChanged("MaxRegistration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int CurrentlyRegistered {
            get {
                return this.currentlyRegisteredField;
            }
            set {
                this.currentlyRegisteredField = value;
                this.RaisePropertyChanged("CurrentlyRegistered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int Waitlist {
            get {
                return this.waitlistField;
            }
            set {
                this.waitlistField = value;
                this.RaisePropertyChanged("Waitlist");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string TrainingContact {
            get {
                return this.trainingContactField;
            }
            set {
                this.trainingContactField = value;
                this.RaisePropertyChanged("TrainingContact");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultCurriculum : CatalogResult {
        
        private LoDetailsWithinCurriculum[] loDetailsField;
        
        private SectionDetail[] sectionDetailsField;
        
        private Field[] fieldsField;
        
        private string curriculumPriceCurrencyField;
        
        private decimal curriculumPriceAmountField;
        
        private string curriculumTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public LoDetailsWithinCurriculum[] LoDetails {
            get {
                return this.loDetailsField;
            }
            set {
                this.loDetailsField = value;
                this.RaisePropertyChanged("LoDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SectionDetail[] SectionDetails {
            get {
                return this.sectionDetailsField;
            }
            set {
                this.sectionDetailsField = value;
                this.RaisePropertyChanged("SectionDetails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CurriculumPriceCurrency {
            get {
                return this.curriculumPriceCurrencyField;
            }
            set {
                this.curriculumPriceCurrencyField = value;
                this.RaisePropertyChanged("CurriculumPriceCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal CurriculumPriceAmount {
            get {
                return this.curriculumPriceAmountField;
            }
            set {
                this.curriculumPriceAmountField = value;
                this.RaisePropertyChanged("CurriculumPriceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CurriculumType {
            get {
                return this.curriculumTypeField;
            }
            set {
                this.curriculumTypeField = value;
                this.RaisePropertyChanged("CurriculumType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultTest : CatalogResult {
        
        private Field[] fieldsField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
    public partial class CatalogResultOnlineCourse : CatalogResult {
        
        private Field[] fieldsField;
        
        private string priceCurrencyField;
        
        private decimal priceAmountField;
        
        private string durationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PriceCurrency {
            get {
                return this.priceCurrencyField;
            }
            set {
                this.priceCurrencyField = value;
                this.RaisePropertyChanged("PriceCurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal PriceAmount {
            get {
                return this.priceAmountField;
            }
            set {
                this.priceAmountField = value;
                this.RaisePropertyChanged("PriceAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetails", WrapperNamespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService", IsWrapped=true)]
    public partial class GetDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService")]
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService", Order=0)]
        public string object_id;
        
        public GetDetailsRequest() {
        }
        
        public GetDetailsRequest(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.AuthHeader AuthHeader, string object_id) {
            this.AuthHeader = AuthHeader;
            this.object_id = object_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDetailsResponse", WrapperNamespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService", IsWrapped=true)]
    public partial class GetDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/GetDetailsWebService", Order=0)]
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.CatalogResult GetDetailsResult;
        
        public GetDetailsResponse() {
        }
        
        public GetDetailsResponse(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.CatalogResult GetDetailsResult) {
            this.GetDetailsResult = GetDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetDetailsWebServiceSoapChannel : IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsWebServiceSoapClient : System.ServiceModel.ClientBase<IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap>, IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap {
        
        public GetDetailsWebServiceSoapClient() {
        }
        
        public GetDetailsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDetailsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDetailsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDetailsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap.GetDetails(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest request) {
            return base.Channel.GetDetails(request);
        }
        
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.CatalogResult GetDetails(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.AuthHeader AuthHeader, string object_id) {
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest inValue = new IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.object_id = object_id;
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse retVal = ((IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap)(this)).GetDetails(inValue);
            return retVal.GetDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse> IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap.GetDetailsAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest request) {
            return base.Channel.GetDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsResponse> GetDetailsAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.AuthHeader AuthHeader, string object_id) {
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest inValue = new IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.object_id = object_id;
            return ((IFDS.KMPortal.PACEPartnerJob.PACEPartnerServiceDetails.GetDetailsWebServiceSoap)(this)).GetDetailsAsync(inValue);
        }
    }
}
