//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFDS.KMPortal.PACEPartnerJob.PACEPartnerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog", ConfigurationName="PACEPartnerService.CatalogwebserviceSoap")]
    public interface CatalogwebserviceSoap {
        
        // CODEGEN: Generating message contract since message SearchRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cornerstoneondemand.com/Webservices/Catalog/Search", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse Search(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cornerstoneondemand.com/Webservices/Catalog/Search", ReplyAction="*")]
        System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse> SearchAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class AuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string corpNameField;
        
        private string userIdField;
        
        private string signatureField;
        
        private string headerSaltField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CorpName {
            get {
                return this.corpNameField;
            }
            set {
                this.corpNameField = value;
                this.RaisePropertyChanged("CorpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
                this.RaisePropertyChanged("Signature");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string HeaderSalt {
            get {
                return this.headerSaltField;
            }
            set {
                this.headerSaltField = value;
                this.RaisePropertyChanged("HeaderSalt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OUAvailability))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserAvailability))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class Availability : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private bool includeSubsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IncludeSubs {
            get {
                return this.includeSubsField;
            }
            set {
                this.includeSubsField = value;
                this.RaisePropertyChanged("IncludeSubs");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class OUAvailability : Availability {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class UserAvailability : Availability {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class Subject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string titleField;
        
        private string titleWithHierarchyField;
        
        private string parentIdField;
        
        private string parentTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TitleWithHierarchy {
            get {
                return this.titleWithHierarchyField;
            }
            set {
                this.titleWithHierarchyField = value;
                this.RaisePropertyChanged("TitleWithHierarchy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("ParentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ParentTitle {
            get {
                return this.parentTitleField;
            }
            set {
                this.parentTitleField = value;
                this.RaisePropertyChanged("ParentTitle");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class LoSubject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Subject[] subjectWithHierarchyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Subject[] SubjectWithHierarchy {
            get {
                return this.subjectWithHierarchyField;
            }
            set {
                this.subjectWithHierarchyField = value;
                this.RaisePropertyChanged("SubjectWithHierarchy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class Field : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class CatalogSearchResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Field[] fieldsField;
        
        private LoSubject[] loSubjectListField;
        
        private Availability[] availabilitiesField;
        
        private string objectIdField;
        
        private string courseTitleField;
        
        private CatalogType typeField;
        
        private string providerNameField;
        
        private decimal priceField;
        
        private string descrField;
        
        private string durationField;
        
        private string createdDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Field[] Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
                this.RaisePropertyChanged("Fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public LoSubject[] LoSubjectList {
            get {
                return this.loSubjectListField;
            }
            set {
                this.loSubjectListField = value;
                this.RaisePropertyChanged("LoSubjectList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Availability[] Availabilities {
            get {
                return this.availabilitiesField;
            }
            set {
                this.availabilitiesField = value;
                this.RaisePropertyChanged("Availabilities");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("ObjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CourseTitle {
            get {
                return this.courseTitleField;
            }
            set {
                this.courseTitleField = value;
                this.RaisePropertyChanged("CourseTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CatalogType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ProviderName {
            get {
                return this.providerNameField;
            }
            set {
                this.providerNameField = value;
                this.RaisePropertyChanged("ProviderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
                this.RaisePropertyChanged("Descr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CreatedDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("CreatedDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public enum CatalogType {
        
        /// <remarks/>
        ONLINE = 1,
        
        /// <remarks/>
        EVENT = 2,
        
        /// <remarks/>
        QUICKCOURSE = 4,
        
        /// <remarks/>
        CURRICULUM = 8,
        
        /// <remarks/>
        TEST = 16,
        
        /// <remarks/>
        SESSION = 32,
        
        /// <remarks/>
        LIBRARY = 64,
        
        /// <remarks/>
        POSTING = 128,
        
        /// <remarks/>
        MATERIAL = 256,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class CatalogSearchResultMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CatalogSearchResult[] resultsField;
        
        private int totalCountField;
        
        private int pageNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public CatalogSearchResult[] Results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
                this.RaisePropertyChanged("Results");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalCount {
            get {
                return this.totalCountField;
            }
            set {
                this.totalCountField = value;
                this.RaisePropertyChanged("TotalCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int PageNum {
            get {
                return this.pageNumField;
            }
            set {
                this.pageNumField = value;
                this.RaisePropertyChanged("PageNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
    public partial class CatalogSearchQuery : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] locationOuIdsField;
        
        private string objectIdField;
        
        private string titleField;
        
        private string providerField;
        
        private int pageNumField;
        
        private string subjectField;
        
        private string competenciesField;
        
        private string descrField;
        
        private CatalogType typeField;
        
        private int locatorNumberField;
        
        private string locationsField;
        
        private string instructorField;
        
        private string createdDateStartField;
        
        private string createdDateEndField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] LocationOuIds {
            get {
                return this.locationOuIdsField;
            }
            set {
                this.locationOuIdsField = value;
                this.RaisePropertyChanged("LocationOuIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ObjectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
                this.RaisePropertyChanged("ObjectId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Provider {
            get {
                return this.providerField;
            }
            set {
                this.providerField = value;
                this.RaisePropertyChanged("Provider");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int PageNum {
            get {
                return this.pageNumField;
            }
            set {
                this.pageNumField = value;
                this.RaisePropertyChanged("PageNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Competencies {
            get {
                return this.competenciesField;
            }
            set {
                this.competenciesField = value;
                this.RaisePropertyChanged("Competencies");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Descr {
            get {
                return this.descrField;
            }
            set {
                this.descrField = value;
                this.RaisePropertyChanged("Descr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CatalogType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int LocatorNumber {
            get {
                return this.locatorNumberField;
            }
            set {
                this.locatorNumberField = value;
                this.RaisePropertyChanged("LocatorNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Locations {
            get {
                return this.locationsField;
            }
            set {
                this.locationsField = value;
                this.RaisePropertyChanged("Locations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string Instructor {
            get {
                return this.instructorField;
            }
            set {
                this.instructorField = value;
                this.RaisePropertyChanged("Instructor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CreatedDateStart {
            get {
                return this.createdDateStartField;
            }
            set {
                this.createdDateStartField = value;
                this.RaisePropertyChanged("CreatedDateStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CreatedDateEnd {
            get {
                return this.createdDateEndField;
            }
            set {
                this.createdDateEndField = value;
                this.RaisePropertyChanged("CreatedDateEnd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Search", WrapperNamespace="http://www.cornerstoneondemand.com/Webservices/Catalog", IsWrapped=true)]
    public partial class SearchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog")]
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.AuthHeader AuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog", Order=0)]
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchQuery query;
        
        public SearchRequest() {
        }
        
        public SearchRequest(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.AuthHeader AuthHeader, IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchQuery query) {
            this.AuthHeader = AuthHeader;
            this.query = query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SearchResponse", WrapperNamespace="http://www.cornerstoneondemand.com/Webservices/Catalog", IsWrapped=true)]
    public partial class SearchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cornerstoneondemand.com/Webservices/Catalog", Order=0)]
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchResultMessage SearchResult;
        
        public SearchResponse() {
        }
        
        public SearchResponse(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchResultMessage SearchResult) {
            this.SearchResult = SearchResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatalogwebserviceSoapChannel : IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogwebserviceSoapClient : System.ServiceModel.ClientBase<IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap>, IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap {
        
        public CatalogwebserviceSoapClient() {
        }
        
        public CatalogwebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogwebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogwebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogwebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap.Search(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest request) {
            return base.Channel.Search(request);
        }
        
        public IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchResultMessage Search(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.AuthHeader AuthHeader, IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchQuery query) {
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest inValue = new IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.query = query;
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse retVal = ((IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap)(this)).Search(inValue);
            return retVal.SearchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse> IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap.SearchAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest request) {
            return base.Channel.SearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchResponse> SearchAsync(IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.AuthHeader AuthHeader, IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogSearchQuery query) {
            IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest inValue = new IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.SearchRequest();
            inValue.AuthHeader = AuthHeader;
            inValue.query = query;
            return ((IFDS.KMPortal.PACEPartnerJob.PACEPartnerService.CatalogwebserviceSoap)(this)).SearchAsync(inValue);
        }
    }
}
