//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IFDS.KMPortal.Webparts.FrequentlyUsedDocsWebPart {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class FrequentlyUsedDocsWebPart {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "12.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(FrequentlyUsedDocsWebPart target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__BuildControlTree(global::IFDS.KMPortal.Webparts.FrequentlyUsedDocsWebPart.FrequentlyUsedDocsWebPart @__ctrl) {
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Render__control1));
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void @__Render__control1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n\r\n<script type=\"text/javascript\">\r\n    //<![CDATA[\r\n    var _noDataMessage = \'");
                   @__w.Write(NoDataMessage );

            @__w.Write("\';\r\n    //]]>\r\n</script>\r\n<div id=\"frequentlyUsedWidget\" class=\"widgetWrapperHeig" +
                    "ht\">\r\n    <div class=\"panel-heading tb-border\">\r\n        <div class=\"sub-caption" +
                    "\">\r\n            <span class=\"faqicon\"></span>\r\n            <span class=\"panel-ti" +
                    "tle\">");
                              @__w.Write( _FrequentlyUsedWidgetTitle);

            @__w.Write("</span>\r\n\r\n            <a class=\"help-icon\" href=\"#\" data-placement=\"top\" data-to" +
                    "ggle=\"tooltip\" data-container=\"body\" data-html=\"true\"\r\n                title=\'");
               @__w.Write( _webPartToolTip);

            @__w.Write(@"'></a>

            <a href=""javascript:RedirectFromFrequent();"" class=""more-globl"" id="""">View All</a>
        </div>
    </div>
    <div class=""panel-bgcolor fu-docs outer frq"">
        <div class=""scrolldiv"">
            <div id=""frequentItems_container"">
            </div>
        </div>
    </div>
</div>

<script>
    //<![CDATA[


    var SiteURL;
    var siteURLfdoc;

    siteURLfdoc = _spPageContextInfo.webAbsoluteUrl;

    if (siteURLfdoc !== undefined || siteURLfdoc !== null) {
        SiteURL = siteURLfdoc;
    }
    else {
        SiteURL = '");
            @__w.Write(siteURL );

            @__w.Write("\';\r\n    }\r\n\r\n    var redirectFUDUrl = SiteURL + \"/_Layouts/15/IFDS.KMPortal/ViewA" +
                    "llRecentDocs.aspx\";\r\n\r\n    var ItemCount = \'");
              @__w.Write(itemCount );

            @__w.Write("\';\r\n    var errorMessage = \'");
                 @__w.Write(_ErrMsg );

            @__w.Write("\';\r\n    var currentLoggedInUser = \"\";\r\n    var userid = _spPageContextInfo.userId" +
                    ";\r\n    var webTitle = _spPageContextInfo.webTitle;\r\n    var webPartName = \"Frequ" +
                    "entlyUsedDocuments\";\r\n\r\n    function AddParameter(form, name, value) {\r\n        " +
                    "var $input = $(\"<input />\").attr(\"type\", \"hidden\")\r\n                            " +
                    "    .attr(\"name\", name)\r\n                                .attr(\"value\", value);\r" +
                    "\n        form.append($input);\r\n    }\r\n\r\n    function RedirectFromFrequent() {\r\n " +
                    "       //Create a Form        \r\n        var $form = $(\"<form/>\").attr(\"id\", \"dat" +
                    "a_form_frequent\")\r\n                        .attr(\"action\", redirectFUDUrl)\r\n    " +
                    "                    .attr(\"target\", \"_blank\")\r\n                        .attr(\"me" +
                    "thod\", \"post\");\r\n        $(\"body\").append($form);\r\n\r\n        //Append the values" +
                    " to be send\r\n        AddParameter($form, \"SiteURL\", SiteURL);\r\n        AddParame" +
                    "ter($form, \"IsRecent\", \'0\');\r\n        AddParameter($form, \"ErrMsg\", errorMessage" +
                    ");\r\n        AddParameter($form, \"WebTitle\", webTitle);\r\n\r\n        //Send the For" +
                    "m\r\n        $form[0].submit();\r\n    }\r\n\r\n    (function ($) {\r\n\r\n        //$(docum" +
                    "ent).ready(function () {\r\n        $(window).load(function () {\r\n            GetF" +
                    "requentlyUsedData();\r\n        });\r\n\r\n        function GetFrequentlyUsedData() {\r" +
                    "\n            var cacheName = webTitle + \"_\" + webPartName;\r\n            $.ajax({" +
                    "\r\n                type: \"POST\",\r\n                contentType: \"application/json;" +
                    " charset=utf-8\",\r\n                url: \"/_Layouts/15/IFDS.KMPortal/WebMethodHelp" +
                    "er.aspx/GetFrequentlyUsedDocuments\",\r\n                data: \'{ siteURL: \\\'\' + Si" +
                    "teURL + \'\\\', itemCount: \\\'\' + ItemCount + \'\\\', cacheName:\\\'\' + cacheName + \'\\\'  " +
                    ", errMSG:\\\'\' + errorMessage + \'\\\' }\',\r\n                success: function (msg) {" +
                    "\r\n                    BindFrequentlyUsedData(JSON.parse(msg.d), \'#frequentItems_" +
                    "container\');\r\n                },\r\n                error: function (msg) {\r\n     " +
                    "               //alert(\'error :\' + msg);\r\n                }\r\n            });\r\n  " +
                    "      }\r\n\r\n        function BindFrequentlyUsedData(jsonData, controlID) {\r\n     " +
                    "       var html = [];\r\n            var errorMessage = jsonData[1].Message;\r\n    " +
                    "        if (errorMessage.length > 0) {\r\n                $(controlID).html(errorM" +
                    "essage);\r\n            }\r\n            else if (jsonData[0].Results === undefined " +
                    "|| jsonData[0].Results === null || jsonData[0].Results.length == 0) {\r\n         " +
                    "       $(controlID).append(_noDataMessage);\r\n            }\r\n            else {\r\n" +
                    "                $.each(jsonData[0].Results, function (index, element) {\r\n\r\n     " +
                    "               html = html + \'<div class=\"docinfo\"><div class=\"img-txt\"><div><im" +
                    "g src=\' + element.iconURL + \' alt=\"icon\"> \'\r\n                                + \'" +
                    "<a class=\"skyblue\" href=\\\'\' + element.itemURL + \'\\\' target=\"_blank\">\' + element." +
                    "Title + \'</a>\'\r\n                                + \'</div></div><div class=\"useri" +
                    "nfo-txt\"><div class=\"usrinfo-box\">\'\r\n                                + \'<a href=" +
                    "\"#\" class=\"pull-left\"><span class=\"blue user-txt-detail\">\' + element.Author + \'<" +
                    "/span></a>\'\r\n                                + \'<div class=\"icon-time-user\"><spa" +
                    "n class=\"glyphicon glyphicon-time bdn\" aria-hidden=\"true\">\'\r\n                   " +
                    "             + \'<span class=\"icon-txt\">\' + element.modifiedDate + \'</span></span" +
                    ">\'\r\n                                + \'<a href=\"#\" onClick=\"TriggerOutlook(\\\'\' +" +
                    " element.itemAbsoluteURL + \'\\\');\" class=\"mail-icon\"></a>\'\r\n                     " +
                    "           + \'</div></div></div></div>\';\r\n                });\r\n\r\n               " +
                    " $(controlID).html(html);\r\n            }\r\n        }\r\n\r\n    })(jQuery);\r\n    //]]" +
                    ">\r\n</script>\r\n");
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "12.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
